# Generated by Django 3.0.1 on 2019-12-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Job_Title', models.CharField(blank=True, max_length=30)),
                ('BioData', models.TextField(blank=True)),
            ],
        ),
    ]
